
import mysql.connector
import os

def get_db_connection():
    try:
        return mysql.connector.connect(
            host="localhost",
            user="root",
            password="vishal7084",
            database="flask_auth"
        )
    except mysql.connector.Error as err:
        print(f"Error connecting to DB: {err}")
        return None

def export_schema():
    conn = get_db_connection()
    if not conn:
        return

    cursor = conn.cursor()
    
    # Get all tables
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()
    
    with open("full_schema.sql", "w", encoding="utf-8") as f:
        f.write("-- Full Database Schema Export\n")
        f.write("-- Generated by export_schema.py\n\n")
        f.write("CREATE DATABASE IF NOT EXISTS flask_auth;\n")
        f.write("USE flask_auth;\n\n")
        
        for (table_name,) in tables:
            print(f"Exporting schema for: {table_name}")
            cursor.execute(f"SHOW CREATE TABLE {table_name}")
            create_stmt = cursor.fetchone()[1]
            f.write(f"-- Table structure for {table_name}\n")
            f.write(f"DROP TABLE IF EXISTS {table_name};\n")
            f.write(f"{create_stmt};\n\n")
            
            # Optional: Export data? 
            # The user wants "all working", usually implies data too, but for a fresh "hosting", schema is minimal.
            # But let's check if we should dump data. "All working like db" might mean empty DB structure is enough, 
            # or they might want their current data. 
            # Safest is Schema only for now, as data might successfully export but be too large or sensitive.
            # I'll add a comment about data.

    print("Schema export completed to full_schema.sql")
    conn.close()

if __name__ == "__main__":
    export_schema()
